config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  #get 'order_items/create'
  #get 'order_items/update'
  #get 'order_items/destroy'

  #get 'carts/show'

  resource :cart, only: [:show, :update, :edit, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  patch "/cart", to: "orders#update", as: "update_order"

  resources :farmers, param: :slug

  resources :coffees, param: :slug

  resources :newsletters, only: [:create]

  get "/about-us", to: "pages#about_us", as: "about_us"

  get "/mission-vision", to: "pages#mission_vision", as: "mission_vision"

  get "/general-terms-of-trade", to: "pages#general_terms_of_trade", as: "general_terms_of_trade"

  get "/privacy-policy", to: "pages#privacy_policy", as: "privacy_policy"

  get "/impressum", to: "pages#impressum", as: "impressum"

  get "/order-successful", to: "pages#order_successful", as: "order_successful"




  #post 'newsletters', to: 'newsletters#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coffee.rb
class Coffee < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :farmer

  mount_uploader :flavor1_image, PhotoUploader
  mount_uploader :flavor2_image, PhotoUploader
  mount_uploader :flavor3_image, PhotoUploader

  has_many :order_items

  default_scope { where(active: true) }
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController

  before_action :authenticate_user!

  #needs to be added at some point

  ##before_action :is_admin?, only: [:update. :destroy]

  def index
    @coffees = Coffee.all
    @order_item = current_order.order_items.new
  end

  def show
    @coffees = Coffee.friendly.find(params[:slug])
  end

  def new
    @coffee = Coffee.new
  end

  def create
    @coffee = Coffee.new(coffee_params)
    @coffee.save
    redirect_to farmers_url
  end

  def edit
  end

  def update
    if @coffee.update(coffee_params)
      redirect_to coffee_path(@coffee)
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def is_admin?
    redirect_to root_path unless current_user.admin?
  end


  def coffee_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
  #  params.require(:coffee).permit(:price, :farmer_id, :active, :name)
    params.require(:coffee).permit(:name, :bags, :process, :certification, :year, :price, :price2, :sku, :farmer_id, :packaging, :sample_packaging, :batch, :score, :variety, :screensize, :flavor1, :flavor2, :flavor3, :flavor1_image, :flavor2_image, :flavor3_image, :cup_description)
  end

  def set_coffee
    @coffee = Coffee.friendly.find(params[:slug])
  end
end

app/views/coffees/_coffee_row.html.erb
<tr>
  <td class="td-basic"><%= coffee.batch %></td>
  <td class="td-basic"><%= coffee.farmer.farm_name %></td>
  <td class="td-basic"><%= coffee.bags %></td>
  <td class="td-basic">Spot</td>
  <td class="td-basic"><%= coffee.process %></td>
  <td class="td-basic"><%= coffee.year %></td>
  <td class="td-basic"><%= coffee.score %></td>
  <td class="td-basic"><%= coffee.price %></td>
  <td class="td-basic th-last-right"><%= coffee.price2 %></td>
  <td class="no-padding-button td-fixed fixed-td-col">
    <div class="popup-container-country">
      <div class="link-box-spotlist-popup box">
        <div class="spotlist-a">
          <a class="button vertical-align-link-a-spotlist" href="#<%= coffee.slug %>">Bestellen</a>
        </div>
      </div>
      <div id="<%= coffee.slug %>" class="overlay">
        <div class="popup">
          <div class="popup-heading">
            <span class="center-heading">Über <%= coffee.batch %> </span>
          </div>
          <a class="close" href="/coffees" style="background-color: white;">&times;</a>
          <div class="content-farm">
              <p><%= coffee.farmer.long_description.first(400) %>...   <a href="farmers/<%= coffee.farmer.id %>">Mehr Erfahren</a>
              </p>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <h6>Über die Farm</h6>
              <ul class="top">
                <li>
                  <p class="technical-info-popup">Farm:</p><p><%= coffee.farmer.farm_name %></p>
                </li>
                <li>
                  <p class="technical-info-popup">Farmer:</p><p><%= coffee.farmer.first_name %> <%= coffee.farmer.last_name %></p>
                </li>
                <li>
                  <p class="technical-info-popup">Ursprung:</p><p><%= coffee.farmer.origin %></p>
                </li>
                <li>
                  <p class="technical-info-popup">Region:</p><p><%= coffee.farmer.region %></p>
                </li>
              </ul>
              <h6>About the Coffee</h6>
              <ul>
                <li>
                  <p class="technical-info-popup">Sorte:</p><p><%= coffee.variety %></p>
                </li>
                <li>
                  <p class="technical-info-popup">Prozess:</p><p><%= coffee.process %></p>
                </li>
                <% if coffee.certification == "" %>
                <% else coffee.certification.nil? == false %>
                  <li>
                    <p class="technical-info-popup">Zertifikationen:</p><p><%= coffee.certification%></p>
                  </li>
                <% end %>
                <li>
                  <p class="technical-info-popup">Jahr:</p><p><%= coffee.year %></p>
                </li>
                <li>
                  <p class="technical-info-popup">Sack Größe:</p><p><%= coffee.packaging %></p>
                </li>
                <li>
                  <p class="technical-info-popup">Cup score:</p><p><%= coffee.score %></p>
                </li>
                <li>
                  <p class="technical-info-popup">Größe:</p><p><%= coffee.screensize %></p>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <h6>Geschmacksprofil</h6>
              <ul class="top">
                <li>
                  <p class="technical-info-popup">Cup Profil:</p><p><%= coffee.flavor1 %>, <%= coffee.flavor2 %>, <%= coffee.flavor3 %></p>
                </li>
                <li>
                  <p class="technical-info-popup" style="margin-bottom: 0;">Cup Beschreibung:</p>
                </li>
                <li>
                  <p class="cup_description"><%= coffee.cup_description %></p>
                </li>
              </ul>
              <h6>Price & Purchase</h6>
              <ul>
                <li>
                  <p class="technical-info-popup">1+ Säcke:</p><p><%= coffee.price %> Euro</p>
                </li>
                <li>
                  <p class="technical-info-popup">5+ Säcke:</p><p><%= coffee.price2 %> Euro</p>
                </li>
              </ul>

                <%= form_for @order_item do |f| %>
                  <div class="input-group">
                    <div class="bag_amount">
                      <%= f.number_field :quantity, value: 0, class: "number_field_bags", min: 0 %>
                      <span>Säcke zum Warenkorb</span>
                    </div>
                    <div class="sample_wanted">
                      <%= f.check_box :sample, class: "regular-checkbox" %>
                      <span>Sample erwünscht</span>
                    </div>
                    <div class="button-order-input-group">
                      <div class="input-group-btn">
                        <%= f.hidden_field :coffee_id, value: coffee.id %>
                        <%= f.submit "Hinzufügen", class: "btn btn-primary button-order-input-padding" %>
                      </div>
                    </div>
                  </div>
                <% end %>



            </div>
          </div>
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/coffees/_coffee_row_backup.html.erb
<div class="coffee-shop-container">
  <div class="row">
    <div class="col-xs-12 coffee-index-container">
      <div class="coffee-index-section">
        <h5>Facts</h5>
        <p class="facts-p-margins">Farm: <%= coffee.name %></p>
        <p class="facts-p-margins">Origin:</p>
        <p class="facts-p-margins">Crop Year:</p>
        <p class="facts-p-margins">Grade:</p>
        <p class="facts-p-margins">Variety:</p>
        <p class="facts-p-margins">Process type:</p>
        <p class="facts-p-margins">Packaging:</p>
        <p class="facts-p-margins">Screensize:</p>
        <p class="facts-p-margins">Cup-Score:</p>
      </div>
      <div class="coffee-index-section">
        <h5>Flavor</h5>
        <p>Coffee with good sweetness, velvety body and delicate acidity.</p>
        <p>Caramell and Vanilla notes.</p>
        <p>Medium Body.</p>
      </div>
      <div class="coffee-index-section">
        <%= form_for @order_item do |f| %>
          <h5>Pricing</h5>
          <span class="pricing-span-style">1+ Bags:</span> <span>5 Euros</span>
          <br>
          <span class="pricing-span-style">5+ Bags:</span> <span>5 Euros</span>
          <br>

          <span><%= number_to_currency coffee.price %></span>
          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
              <div class="input-group-btn">
                <%= f.hidden_field :coffee_id, value: coffee.id %>
                <%= f.submit "Add to Cart", class: "btn btn-primary" %>
              </div>
          </div>

        <% end %>
      </div>


    </div>
  </div>
</div>

<!--
  <div class="row">
    <div class="col-xs-8">
      <h4><%= coffee.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for @order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency coffee.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :coffee_id, value: coffee.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
-->

app/views/coffees/_navbar_backup.html.erb
<div class="navbar_coffee_container">
  <h3 class="navbar_coffee_header">Coffee Spotlist</h3>
    <div class="row">
      <div class="navbar_link_container">
        <div class="col-xs-12 col-sm-4 no_row_padding">
          <div class="navbar_coffee_text_left coffee_link">
            <a href="coffees" class="coffee_link_a">Our Coffees</a>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 no_row_padding">
          <div class="navbar_coffee_text_center coffee_link">
            <a href="" class="coffee_link_a">Your Contracts</a>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4 no_row_padding">
          <div class="navbar_coffee_text_right coffee_link">
            <%= link_to "#{current_order.order_items.size} bags in Cart", cart_path, class: "coffee_link_a" %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/coffees/_navbar_coffee.html.erb
<div class="spotlist-navbar-container">
  <h5>Spotlist - Brazilian Specialty</h5>
  <div class="row">
    <div class="col-sm-6 col-xs-12 spotlist-navbar-segment">
      <a class="navbar-spotlist-buttons" href="/coffees">Spotlist</a>
    </div>
    <div class="col-sm-6 col-xs-12 spotlist-navbar-segment">

      <% if current_order.bags >= 1 %>
        <% if current_order.bags == 1 %>
          <a class="navbar-spotlist-buttons" href="/cart"><%=  current_order.bags %> Sack im Einkaufswagen</a>
        <% else %>
          <a class="navbar-spotlist-buttons" href="/cart"><%=  current_order.bags %> Säcke im Einkaufswagen</a>
        <% end %>
      <% elsif current_order.order_items.count >= 1 %>
        <% if current_order.order_items.count == 1 %>
          <a class="navbar-spotlist-buttons" href="/cart"><%=  current_order.order_items.count %> Probe im Einkaufswagen</a>
        <% else %>
          <a class="navbar-spotlist-buttons" href="/cart"><%=  current_order.order_items.count %> Proben im Einkaufswagen</a>
        <% end %>
      <% else %>
        <a class="navbar-spotlist-buttons" href="/cart">Hier gehts zum Einkaufswagen</a>
      <% end %>
    </div>
    <!-- <div class="col-sm-4 col-xs-12 spotlist-navbar-segment">
      <a class="navbar-spotlist-buttons" href="/coffees">My Contracts</a>
    </div> -->
  </div>

</div>

app/views/coffees/_simple_form_for_coffees.html.erb
<div class="white-box white-box-coffee-new" style="background-color: light-gray;">
  <div class="form-header">
    <h5>Create a new Coffee - make sure to put in the right farmer id.</h5>
    <p>Please fill out everybox below</p>
  </div>
  <div class="form">
    <div class="form-field">
      <%= simple_form_for @coffee do |c| %>
        <%= c.input :name, class: "form-control" %>
        <%= c.input :bags, class: "form-control" %>
        <%= c.input :process, class: "form-control" %>
        <%= c.input :certification, class: "form-control" %>
        <%= c.input :year, class: "form-control" %>
        <%= c.input :price, class: "form-control" %>
        <%= c.input :price2, class: "form-control" %>
        <%= c.input :sku, class: "form-control"%>
        <%= c.input :farmer_id, class: "form-control"%>
        <%= c.input :cup_description, class: "form-control"%>
        <%= c.input :sample_packaging, class: "form-control"%>
        <%= c.input :packaging %>
        <%= c.input :batch %>
        <%= c.input :score %>
        <%= c.input :variety %>
        <%= c.input :screensize %>
        <%= c.input :flavor1 %>
        <%= c.input :flavor2 %>
        <%= c.input :flavor3 %>
        <%= c.input :flavor1_image %>
        <%= c.input :flavor2_image %>
        <%= c.input :flavor3_image %>
        <%= c.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/coffees/edit.html.erb
<h2>Edit Coffee</h2>

<%= render "simple_form_for_farmer", title: "Edit the farmer", button_text: "Edit Farmer" %>

app/views/coffees/index.html.erb
<%= render 'navbar_coffee' %>

<div class="spotlist-container">
  <table class="spotlist">
    <thead>
      <tr>
        <th class="th-basic-first">Referenz</th>
        <th class="th-basic">Fazenda</th>
        <th class="th-basic">Säcke</th>
        <th class="th-basic">Verfügbarkeit</th>
        <th class="th-basic">Prozess</th>
        <th class="th-basic">Jahr</th>
        <th class="th-basic">Cup - Score</th>
        <th class="th-basic">Preis 1+ Säcke</th>
        <th class="th-basic">Preis 5+ Säcke</th>
        <th class="th-fixed fixed-col"></th>
      </tr>
    </thead>
    <% @coffees.each do |coffee| %>
      <% if coffee.bags > 0 %>
        <%= render "coffee_row", coffee: coffee, order_item: @order_item %>
      <% else %>
      <% end %>
    <% end %>
  </table>
</div>

<%= render 'shared/follow_us_footer' %>



<!--<% @coffees.each do |coffee| %>
  <p><%= coffee.bags %></p>
<% end %>

<a class="button-learn-more" href="/coffees/new">New Coffee</a>

<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h1><%= link_to "My Store", coffees_path %></h1>
    </div>
    <div class="col-xs-6 text-right">
    </div>
  </div>
  <hr>
</div>
-->

app/views/coffees/new.html.erb
<h2>Create new user</h2>
<%= render "simple_form_for_coffees", title: "Add a Coffee", button_text: "Add Coffee" %>