config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  #get 'order_items/create'
  #get 'order_items/update'
  #get 'order_items/destroy'

  #get 'carts/show'

  resource :cart, only: [:show, :update, :edit, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  patch "/cart", to: "orders#update", as: "update_order"

  resources :farmers, param: :slug

  resources :coffees, param: :slug

  resources :newsletters, only: [:create]

  get "/about-us", to: "pages#about_us", as: "about_us"

  get "/mission-vision", to: "pages#mission_vision", as: "mission_vision"

  get "/general-terms-of-trade", to: "pages#general_terms_of_trade", as: "general_terms_of_trade"

  get "/privacy-policy", to: "pages#privacy_policy", as: "privacy_policy"

  get "/impressum", to: "pages#impressum", as: "impressum"

  get "/order-successful", to: "pages#order_successful", as: "order_successful"




  #post 'newsletters', to: 'newsletters#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order = current_order
    @order_items = current_order.order_items
  end

  def update
    @order = current_order
    if @order.update(order_params)

      order = current_order
      order_items = current_order.order_items

      #Update trigger for mail - check for validations
      company_name = params[:order][:company_name]
      customer_first_name = params[:order][:customer_first_name]
      customer_last_name = params[:order][:customer_last_name]
      customer_email = params[:order][:customer_email]
      phone_number = params[:order][:phone_number]
      customer_billing_address = params[:order][:customer_billing_address]
      customer_billing_postcode = params[:order][:customer_billing_postcode]
      customer_billing_city = params[:order][:customer_billing_city]
      customer_billing_country = params[:order][:customer_billing_country]
      vat_number = params[:order][:vat_number]
      special_request = params[:order][:special_request]

      OrderMailer.order_email(company_name, customer_first_name, customer_last_name, customer_email, phone_number, customer_billing_address, customer_billing_postcode, customer_billing_city, customer_billing_country, vat_number, special_request, order, order_items).deliver

      #add confirmation link below this

      redirect_to order_successful_path

      #flash does not work yet

      reset_session

    else
      redirect_to cart_path
    end
  end

  private

  def order_params
    params.require(:order).permit(:company_name, :customer_first_name, :customer_last_name, :phone_number, :customer_email, :customer_billing_address, :customer_billing_postcode, :customer_billing_city, :customer_billing_country, :customer_billing_state, :vat_number, :special_request)
  end

end

app/views/carts/_cart_order_items.html.erb
<div class="order_item_container">
  <span class="header_for_table">Spot-list Bestellung</span>
  <table class="order_items_table">
    <thead>
      <tr>
        <th class="order_items_th_basic">Referenz</th>
        <th class="order_items_th_basic">Fazenda</th>
        <th class="order_items_th_basic">Sorte</th>
        <th class="order_items_th_basic">Menge</th>
        <th class="order_items_th_basic">Säcke</th>
        <th class="order_items_th_basic">Stückpreis</th>
        <th>     </th>
      </tr>
    </thead>
    <% @order_items.each do |order_item| %>
      <% if order_item.quantity > 0 %>
        <%= render "order_items_row", order_item: order_item %>
      <% else %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/carts/_cart_row.html.erb
  <div class="row">
    <div class="col-xs-8">
      <h4><%= coffee.variety %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :coffee_id, value: coffee.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Remove", order_item_path(order_item), method: :delete, href:"javascript:window.location.href=window.location.href" %>
              <!-- { method: :delete, remote: true, class: "btn btn-danger" }
              -->
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>

app/views/carts/_cart_sample_items.html.erb
<div class="order_item_container">
  <span class="header_for_table">Sample Bestellung</span>
  <table class="order_items_table">
    <thead>
      <tr>
        <th class="order_items_th_basic">Referenz</th>
        <th class="order_items_th_basic">Fazenda</th>
        <th class="order_items_th_basic">Sorte</th>
        <th class="order_items_th_basic">Menge</th>
        <th class="order_items_th_basic">Säcke</th>
        <th class="order_items_th_basic">Stückpreis</th>
        <th>     </th>
      </tr>
    </thead>
    <% @order_items.each do |order_item| %>
      <% if order_item.sample == true %>
        <%= render "cart_sample_items_row", order_item: order_item %>
      <% else %>
      <% end %>
    <% end %>
  </table>
</div>

app/views/carts/_cart_sample_items_row.html.erb
<tr>
  <td class="order_items_td_basic"><%= order_item.coffee.batch %></td>
  <td class="order_items_td_basic"><%= order_item.coffee.farmer.farm_name %></td>
  <td class="order_items_td_basic"><%= order_item.coffee.variety %></td>
  <td class="order_items_td_basic"><%= order_item.coffee.sample_packaging%> gr</td>
  <td class="order_items_td_basic">1</td>
  <td class="order_items_td_basic">Free of charge</td>
  <td class="order_items_td_basic order_items_td_last"><%= link_to "Delete", order_item, method: :delete, onClick:"window.location.href=window.location.href" %></td>
</tr>

app/views/carts/_cart_svg.html.erb
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 600 600" style="enable-background:new 0 0 459.529 459.529;" xml:space="preserve">
<g>
  <g>
    <path d="M17,55.231h48.733l69.417,251.033c1.983,7.367,8.783,12.467,16.433,12.467h213.35c6.8,0,12.75-3.967,15.583-10.2
      l77.633-178.5c2.267-5.383,1.7-11.333-1.417-16.15c-3.117-4.817-8.5-7.65-14.167-7.65H206.833c-9.35,0-17,7.65-17,17
      s7.65,17,17,17H416.5l-62.9,144.5H164.333L94.917,33.698c-1.983-7.367-8.783-12.467-16.433-12.467H17c-9.35,0-17,7.65-17,17
      S7.65,55.231,17,55.231z"/>
    <path d="M135.433,438.298c21.25,0,38.533-17.283,38.533-38.533s-17.283-38.533-38.533-38.533S96.9,378.514,96.9,399.764
      S114.183,438.298,135.433,438.298z"/>
    <path d="M376.267,438.298c0.85,0,1.983,0,2.833,0c10.2-0.85,19.55-5.383,26.35-13.317c6.8-7.65,9.917-17.567,9.35-28.05
      c-1.417-20.967-19.833-37.117-41.083-35.7c-21.25,1.417-37.117,20.117-35.7,41.083
      C339.433,422.431,356.15,438.298,376.267,438.298z"/>

</svg>

app/views/carts/_form_for_current_order.html.erb
<div class="form_for_current_order_container">
  <span class="your-details-heading">Ihre Details</span>
  <%= form_for @order, url: cart_path do |f| %>
    <div class="order-form">
      <%= f.text_field :company_name, placeholder: "Name Unternehmen", class: 'order-from-input order-input-width' %>
      <%= f.text_field :customer_first_name, placeholder: "Vorname", class: 'order-from-input order-input-width' %>
      <%= f.text_field :customer_last_name, placeholder: "Nachname", class: 'order-from-input order-input-width' %>
      <%= f.text_field :customer_email, placeholder: "Email-adresse", class: 'order-from-input order-input-width' %>
      <%= f.text_field :phone_number, placeholder: "Telefonnummer", class: 'order-from-input order-input-width' %>
      <%= f.text_field :customer_billing_address, placeholder: "Adresse", class: 'order-from-input order-input-width' %>
      <%= f.text_field :customer_billing_postcode, placeholder: "Postleitzahl", class: 'order-from-input order-input-width' %>
      <%= f.text_field :customer_billing_city, placeholder: "Stadt", class: 'order-from-input order-input-width' %>
      <%= f.text_field :customer_billing_country, placeholder: "Land", class: 'order-from-input order-input-width' %>
      <%= f.text_field :vat_number, placeholder: "Umsatzsteuer Number", class: 'order-from-input order-input-width' %>
      <%= f.text_field :special_request, placeholder: "Sonstige Anmerkungen", class: 'order-from-input order-input-width' %>
      <%= f.submit "Bestellen", class: 'btn btn-primary' %>

    </div>
    <% end %>

</div>

app/views/carts/_navbar2.html.erb
<div class="spotlist-navbar-container">
  <h5>Finalize your Order</h5>
  <div class="row">
    <div class="col-sm-4 col-xs-12 spotlist-navbar-segment">
      <a class="navbar-spotlist-buttons" href="/coffees">Spotlist</a>
    </div>
    <div class="col-sm-4 col-xs-12 spotlist-navbar-segment">
      <a class="navbar-spotlist-buttons" href="/cart"><%=  current_order.bags %> Bags in Cart</a>
    </div>
    <div class="col-sm-4 col-xs-12 spotlist-navbar-segment">
      <a class="navbar-spotlist-buttons" href="/coffees">My Contracts</a>
    </div>
  </div>

</div>

app/views/carts/_order_items_row.html.erb
<tr>
  <td class="order_items_td_basic"><%= order_item.coffee.batch %></td>
  <td class="order_items_td_basic"><%= order_item.coffee.farmer.farm_name %></td>
  <td class="order_items_td_basic"><%= order_item.coffee.variety %></td>
  <td class="order_items_td_basic"><%= order_item.coffee.packaging %></td>
  <td class="order_items_td_basic"><%= order_item.quantity %></td>
  <td class="order_items_td_basic"><%= order_item.unit_price %> € /kg</td>
  <td class="order_items_td_basic order_items_td_last"><%= link_to "Delete", order_item, method: :delete, onClick:"window.location.href=window.location.href" %></td>
</tr>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center text-of-message-position">
    Es befinden sich momentan keine Gegenstände in Ihrem Einkaufswagen.  Bitte <%= link_to "zur Spotlist", coffees_path %> und fügen Sie Kaffeesäcke oder Proben zu Ihrem Einkaufswagen hinzu.
  </p>
<% else %>
  <% if @order_items.any? { |u| u[:quantity] > 0 } %>
    <%= render 'cart_order_items' %>
  <% end %>

  <% if @order_items.any? { |h| h[:sample] == true } %>
    <%= render 'cart_sample_items' %>
  <% end %>

  <%= render "form_for_current_order" %>

<% end %>

app/views/carts/_shopping_cart_header.html.erb
<div class="spotlist-navbar-container">
  <% if @order_items.any? { |u| u[:quantity] > 0 } %>
    <h5>Schließen Sie Ihre Bestellung ab</h5>

  <% elsif @order_items.any? { |h| h[:sample] == true } %>
    <h5>Schließen Sie Ihre Bestellung ab</h5>
  <% else %>
    <h5>Ihr Einkaufswagen</h5>
  <% end %>



</div>

app/views/carts/show.html.erb
<div class="cart_wrapper">
  <%= render "shopping_cart_header" %>
  <%= render "shopping_cart" %>
</div>
  <%= render 'shared/follow_us_footer' %>